### ISSUE TITLE
Investigate failure with XGBoost

### ISSUE THREAD

**Issue by Zukkari** [Zukkari/nirdizati-training-ui#89]
Whenever job with XGBoost is run, following error is produced:
```<2017-12-22 22:22:26,832> <DEBUG> <SimulationJob.class:76> <Script call: [/home/stanislav/anaconda3/bin/python, train.py, BPIC15_4.csv, zero, agg, xgb, remtime]>
/home/stanislav/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py:4281: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
(53792, 27)
(13491, 27)
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
Bucketing prefixes...
Fitting pipeline for bucket 1...
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    pipelines[bucket].fit(dt_train_bucket, train_y)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 248, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 213, in _fit
    **fit_params_steps[name])
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py", line 362, in __call__
    return self.func(*args, **kwargs)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 581, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 739, in fit_transform
    for name, trans, weight in self._iter())
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 581, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 520, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/home/stanislav/git/nirdizati-training-ui/PredictiveMethods/transformers/AggregateTransformer.py", line 28, in transform
    dt_numeric = X.groupby(self.case_id_col)[self.num_cols].agg({'mean':np.mean, 'max':np.max, 'min':np.min, 'sum':np.sum, 'std':np.std})
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py", line 4281, in aggregate
    return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py", line 3714, in aggregate
    result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/pandas/core/base.py", line 461, in _aggregate
    result = _agg(arg, lambda fname,
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/pandas/core/base.py", line 429, in _agg
    result[fname] = func(fname, agg_how)
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/pandas/core/base.py", line 462, in <lambda>
    agg_how: _agg_1dim(self._selection, agg_how))
  File "/home/stanislav/anaconda3/lib/python3.6/site-packages/pandas/core/base.py", line 410, in _agg_1dim
    raise SpecificationError("nested dictionary is ambiguous "
pandas.core.base.SpecificationError: nested dictionary is ambiguous in aggregation
<2017-12-22 22:23:01,872> <DEBUG> <SimulationJob.class:85> <Script finished running...>```

**Comment by verenich** [comment]
the issue does not appear anymore after making these changes:
https://github.com/Zukkari/nirdizati-training-ui/commit/e4c25ffb271c9c632983556aa925912c926fefdc#diff-9106d6f11958d5802ba49acf4bfec9b3

**Comment by Zukkari** [comment]
Issue is fixed and longer appears.
